### ISSUE TITLE
Manual download link is broken

### ISSUE THREAD

**Issue by Ansury** [IvanTrendafilov/Confucius#7]
Section of front page: 

"First, you need the Confucius jar file on your classpath. Confucius is available from Maven Central, so add to your pom.xml (or manually download ..."  <--- this link on front page

**Comment by IvanTrendafilov** [comment]
Please use http://repo1.maven.org/maven2/org/trendafilov/confucius/confucius/1.2.2/

**Comment by Ansury** [comment]
Oh I got a hold of it just fine, just letting you know about the link. :)
